language: python
cache: pip

python:
 - "3.7"
 - "3.8"

env:
  - DJANGO=2.2 CMIS_BINDING=BROWSER
  - DJANGO=2.2 CMIS_BINDING=WEBSERVICE
  # - DJANGO=3.0 CMIS_BINDING=BROWSER
  # - DJANGO=3.0 CMIS_BINDING=WEBSERVICE

install:
  - pip install tox tox-travis

before_script:
  - cd alfresco
  - docker-compose up -d
  - cd ../

script:
  - tox

after_script:
  - cd alfresco && docker-compose stop

after_success:
  - pip install codecov
  - export envname=py${TRAVIS_PYTHON_VERSION/./}-django${DJANGO/./}-$(echo $CMIS_BINDING | tr '[:upper:]' '[:lower:]')
  - codecov -e TOXENV,DJANGO --file reports/coverage-${envname}.xml

jobs:
  fast_finish: true
  include:
    - stage: test
      python: "3.7"
      env: TOXENV=isort
      before_install: skip
      before_script: skip
      after_script: skip
      after_success: skip

    - python: "3.7"
      env: TOXENV=black
      before_install: skip
      before_script: skip
      after_script: skip
      after_success: skip

    - python: "3.7"
      env: TOXENV=flake8
      before_install: skip
      before_script: skip
      after_script: skip
      after_success: skip

    # - python: "3.7"
    #   env: TOXENV=docs
    #   before_install: skip
    #   before_script: skip
    #   after_script: skip
    #   after_success: skip

    - stage: deploy
      name: Deploy to PyPI
      language: python
      before_script: skip
      install: skip
      script: echo "noop"
      deploy:
        provider: pypi
        distributions: sdist bdist_wheel
        user: "__token__"
        password:
          secure: "RC4ijocQVP8Yj7Ie3ODhf+ZesnJq8oazykcagcnDreOPjFtN/omcbMjbt8R4iFxf1Jx9s1TKXF30gYjPVJ0UpU91iHQPs/uyL4uMpev/tN9nECzwJImiIYHArURuq+e+3yIrc5MpAxk0GfJRH8LGvokFtPPcXgcUMD3efZmjJO+k678UHrUfCqrug+lOnu5JVrZYlnceqBU0e6TvekvQuv3AAkyDfwNda3Jv8xGzOhFX1m2gjJRSqfdi/fEf+jI98pH0oKR3hWYVii6W/pGkpuIpa0pUB7co62t0o5m5FtRNDhhOzCCIsrB3SsbMmzbxp+PkATNV9H1a0rFiVvuDwmbreNhbSUD589ksAYINHSUGvYlEsHUbkvGG4oKZxrSnpHphSOaXexNuDeXTWQ6UqIQNU/eovTdjltxDz5vvFQbUMnv4ZfeSMiPgxFGPznXrcYHM8MBOxN+frKr2Yj7o1OIXjgHhR7kuvMMuYtVKrg1Q1sbh3lJ3UMaBpLH+cZUsRlzvwJUoHgsrIFy1U8C12/+zF7uywCRvdHiA6lQDG4uj3u58KBn2zNp/UiQ3vZu19q0j9XeExxwQD37O84p6cIJTykKpVMNeSGfaxHqATwp1o5yNVKeYoXCdWmgtS/vHhT8NTH5YkvoGtCYCQSs6AwjAyAD9UDvayanx2jvBPRk="
        on:
          tags: true
          repo: open-zaak/cmis-adapter
          python: 3.7

stages:
  - test
  - deploy

notifications:
  email: false
