name: Run CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    tags:
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    name: Run the test suite
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8']
        django: ['2.2']
        binding: ['BROWSER', 'WEBSERVICE']

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Bring up Alfresco
        run: cd alfresco && docker-compose up -d

      - name: Install dependencies
        run: pip install tox tox-travis codecov

      - name: Run tests
        run: |
          export TOXENV=py${PYTHON_VERSION/./}-django${DJANGO/./}-$(echo $CMIS_BINDING | tr '[:upper:]' '[:lower:]')
          tox
          codecov -e TOXENV,DJANGO --file reports/coverage-${TOXENV}.xml
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          DJANGO: ${{ matrix.django }}
          CMIS_BINDING: ${{ matrix.binding }}
