name: Run CI

# Run this workflow every time a new commit pushed to your repository
on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8']
        django: ['2.2']
        binding: ['BROWSER', 'WEBSERVICE']

    name: Run the test suite (Python ${{ matrix.python }}, Django ${{ matrix.django }}, ${{ matrix.binding }} binding)

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Bring up Alfresco
        run: cd alfresco && docker-compose up -d

      - name: Install dependencies
        run: pip install tox tox-travis codecov

      - name: Run tests
        run: |
          export TOXENV=py${PYTHON_VERSION/./}-django${DJANGO/./}-$(echo $CMIS_BINDING | tr '[:upper:]' '[:lower:]')
          tox
          codecov -e TOXENV,DJANGO --file reports/coverage-${TOXENV}.xml
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          DJANGO: ${{ matrix.django }}
          CMIS_BINDING: ${{ matrix.binding }}

  tests-urlmappings:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.7', '3.8']
        django: ['2.2']
        binding: ['WEBSERVICE']

    name: Run the test suite (Python ${{ matrix.python }}, Django ${{ matrix.django }}, WEBSERVICE binding with URL mapping)

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}

      - name: Bring up Alfresco
        run: cd alfresco && docker-compose up -d

      - name: Install dependencies
        run: pip install tox tox-travis codecov

      - name: Run tests
        run: |
          export TOXENV=py${PYTHON_VERSION/./}-django${DJANGO/./}-urlmapping
          tox
          codecov -e TOXENV,DJANGO --file reports/coverage-${TOXENV}.xml
        env:
          PYTHON_VERSION: ${{ matrix.python }}
          DJANGO: ${{ matrix.django }}
          CMIS_BINDING: ${{ matrix.binding }}
          IS_URL_MAPPING_ENABLED: True

  publish:
    name: Publish package to PyPI
    runs-on: ubuntu-latest
    needs: [tests, tests-urlmappings]

    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Build sdist and wheel
        run: |
          pip install pip setuptools wheel --upgrade
          python setup.py sdist bdist_wheel

      - name: Publish a Python distribution to PyPI
        uses: pypa/gh-action-pypi-publish@v1.4.1
        with:
          user: __token__
          password: ${{ secrets.PYPI_TOKEN }}
